jobs:
  include:
  # - stage: backend testing
  #   language: node_js
  #   node_js:
  #     - "node"
  #   env:
  #     - NODE_ENV=development
  #   install:
  #     - cd backend
  #     - npm install
  #     - cd ..
  #   script:
  #     - cd backend
  #     - npm test
  #     - cd ..

  - stage: backend deployment
    language: node_js
    node_js:
      - "node"
    script: skip
    env:
      - NODE_ENV=development
    before_deploy:
      - cd backend
    deploy:
      provider: heroku
      api_key: '26ebc65f-3eba-4930-873c-56753fd5a029'
      app: ds-backend
      on:
        all_branches: true
